### ISSUE TITLE
Why do we not offer a 2.0 profile?

### ISSUE THREAD

**Issue by EugenMayer** [evilphish/sennheiser-gsx-1000#11]
While i understand that 7.1 is surely required, i'am not sure why we do not offer a 2.0 digital out?

Maybe i misunderstand this, but if we digitally mix the audio to be 7.1 and then put it into 2.0 mode ( which i always do if listing music), i'am not sure what the GSX does then - does it only select the LEFT/RIGHT channel of the 7.1 output and drops all the others, which will result in great audio loss. Or does the GSX select all channels if incoming is 7.1 and then mixes it all together into 2.0 actively?

So my question is, is there any reason we do not offer a 2.0 profile too?

**Comment by evilphish** [comment]
Hi Eugen,

first of all thanks a lot for your recent commit. :)
Regarding the issue: I believe this is already taken care of by the GSX. It has a dedicated music mode and if you switch to line out you get 2.0 anyway. Afaik the GSX expects input in 7.1 - I have never tried otherwise though. If I listen to music I just turn on music mode on the device.

**Comment by PsychedelicHell** [comment]
Yeah, you can switch to stereo on the device if you wish, but I prefer to listen to it in 7.1 as it sounds wider.
