### ISSUE TITLE
Channel switch fix option not working

### ISSUE THREAD

**Issue by PsychedelicHell** [evilphish/sennheiser-gsx-1000#14]
Hey everyone, 

I'm submitting a quick bug report, I have recently distro hopped from Manjaro to the new Linux Mint 20 beta and I am having channel mixing issues. I previously spoke about having channel mixing issues on Manjaro and a solution was created [here.](https://github.com/evilphish/sennheiser-gsx-1000/issues/9) 

My issue in Linux Mint is still the same, I ran the new installer, selected Y for the channel swap option. However it didn't work, my channels were still center lefty and subwoofer righty. I browsed to /usr/share/pulseaudio/alsa-mixer/profile-sets and found the two sennheiser configs one with the normal name, the other with channelswap. 

However, for whatever reason the channel swap fix wasn't working.

I managed to fix my problem by just editing the sennheiser-gsx-1000.conf with the channel fix lines from the sennheiser-gsx-1000-channelswap.conf

Just wanted to let you guys know in case you wanted to revise your code (I'd love to help further but have no idea what I'm doing).

**Comment by r-contreras** [comment]
Hey @PsychedelicHell, thanks for pointing that out. I had exactly the same issue, but in my case trying the "channel swap fix" option during installation actually made the whole thing not work at all. Just like you said, I did the modifications pointed out in [your previous post](https://github.com/evilphish/sennheiser-gsx-1000/issues/9) and that fixed the channeling issue. I wanted to mention this for all the newbies out there like myself:

- If you try to edit the .config file but can't save the file because its in read-only mode, you've got to open the editor in the terminal with `sudo -H gedit  ./sennheiser-gsx-1000.conf` (assuming you are executing this in the folder where the file is located and you are using the same text editor as me).
- You may try to test the audio after this modification with `speaker-test -c 8` or whatever but unless you restart the whole audio system, you won't notice the changes. As far as I know, in Ubuntu/Pop!OS you can restart it without restarting your computer by running `pulseaudio -k` and waiting a few seconds. I'm sure there's an equivalent command in other distros but can't list them since I don't know them lol.

Please correct me if I'm wrong, I just wanted to post this since I know there may be someone with my knowledge searching for a solution to this whole thing as well. Total noob here, hope this helps :P

Edit: Forgot to add this. Thank you @evilphish and all the contributors for making these amazing DACs work as they should. Great work
