### ISSUE TITLE
just mono channel available

### ISSUE THREAD

**Issue by rkmax** [evilphish/sennheiser-gsx-1000#15]
I have installed and restated, I have the GSX 1000

1. the volume dial does not change the volumen of the system, OK
2. appear two outputs main and chat, OK
3. main output should be 7.1, FAIL

also for some reason in the list of available outputs appear a Null output
![Screenshot from 2020-06-26 12-38-54](https://user-images.githubusercontent.com/395707/85885430-eeaea380-b7a9-11ea-9926-5a64f8548080.png)
![Screenshot from 2020-06-26 12-33-46](https://user-images.githubusercontent.com/395707/85885057-51536f80-b7a9-11ea-9bed-9fc12573f262.png)

**Comment by rkmax** [comment]
Right now the only way to enable 7.1 on my system is adding something like this

```
load-module module-alsa-source device=hw:%cid,0
load-module module-alsa-sink device=hw:%cid,1 channels=8
```

**Comment by rkmax** [comment]
Also reading the profile conf following the note

```
# If you do not want two devices but only one with a switchable profile
# (don't know why you would want that) uncomment the following two
# blocks and comment the one block above this comment.
```

After that appear that is working 
![Screenshot from 2020-06-26 14-07-14](https://user-images.githubusercontent.com/395707/85892288-45ba7580-b7b6-11ea-8376-8a1d02e0ccd4.png)


no need to add 

```
load-module module-alsa-source device=hw:%cid,0
load-module module-alsa-sink device=hw:%cid,1 channels=8
```

**Comment by PsychedelicHell** [comment]
I have this issue too on Linux Mint, for some reason each new audio source defaults to GSX main audio chat output, despite setting main output as the default fallback device.

The way I've worked around it is by installing Pavucontrol and then opening it up with the audio source playing and manually switching it from chat output to main output.

While this is annoying, I do only have to do it once for every new program I use. Though I wish the entire system would default to main output rather than chat output as the only program I use chat output for is Discord.

![image](https://user-images.githubusercontent.com/57477439/85909101-861fff00-b85b-11ea-9b9c-fe33d5073535.png)

**Comment by rkmax** [comment]
after reading a bit pulseaudio documentation and some trial and error I was able to have two outputs which is really nice because I can select comm channel for discord as was intended

![Screenshot from 2020-06-29 13-12-11](https://user-images.githubusercontent.com/395707/86040753-3469a700-ba0a-11ea-98de-8714be546685.png)
![Screenshot from 2020-06-29 13-15-01](https://user-images.githubusercontent.com/395707/86040933-7bf03300-ba0a-11ea-97da-65fa127360eb.png)



as soon I have some time again I'll polish and push my changes

**Comment by rkmax** [comment]
@PsychedelicHell here my changes https://github.com/evilphish/sennheiser-gsx-1000/pull/16, probably you should uninstall the current evilphish installation before in order to avoid conflicts

**Comment by evilphish** [comment]
As mentioned in https://github.com/evilphish/sennheiser-gsx-1000/issues/18 there is a new fix out. Feel free to give it a try and reopen if it does not work for you.
